server:
  port: ${myapp.port:8989}
  servlet:
    context-path: /
    encoding:
      charset: UTF-8
      enabled: true
      force: true
      
spring:
  datasource:
    #mariadb는 자신이 사용하고자 하는 스키마를 입력해야지 들어가짐.
    url: jdbc:mariadb://localhost:3306/security
    username: root
    password: 1234
    driver-class-name: org.mariadb.jdbc.Driver
    
  mvc:
    view:
      prefix: /templates/
      suffix: .mustache

  jpa:
    database-platform: org.hibernate.dialect.MariaDB103Dialect  #JPA가 사용할 database의 dialect 설정
    properties:
      hibernate:
        hibernate:
        "[format_sql]": true            #SQL을 보기 좋게 출력
        "[user_sql_comments]": true     #SQL생성 시 주석 포함
        "[highlight_sql]": true         #SQL에 색깔
        "[hbm2ddl.auto]": update
    open-in-view: false
    show-sql: true

    
  #Spring OAuth
  security:
    oauth2:
     client:
      registration:
       google:
        client-id: 1013147133735-j01tfa0ai92ui0cdlbfl0shquj5b09qk.apps.googleusercontent.com
        client-secret: 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
        scope:
        - email
        - profile
        
       facebook:
        client-id: 6058431824255906
        client-secret: 8fbf42990f549b07de9f8fec80579dac
        scope:
        - email
        - public_profile
          